export default {
  baseUrl: 'http://35.177.56.74:3033/api/',
  imageUrl: 'http://35.177.56.74:3033/images/',
  // baseUrl: 'http://192.168.29.139:3033/api/',
  // imageUrl: 'http://192.168.29.139:3033/images/',
  user: 'user/',
  listRole: 'list-role',
  signup: 'sign-up',
  verifyOTP: 'verify-otp',
  resendOTP: 'resend-otp',
  login: 'login',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  updateUserProfile: 'update-userprofile',
  buildProfile: 'build-profile',
  createJob: 'create-job',
  userJobList: 'job-list-for-user',
  officerJobList: 'job-list-for-officer',
  acceptJob: 'accept-job',
  officersListByJobId: 'officer-approval-list',
  jobListForPending: 'job-list-for-pending',
  jobListForTab: 'job-list-for-tab',
  checkInJobOfOfficer: 'check-in-job-of-officer',
  checkOutJobOfOfficer: 'check-out-job-of-officer',
  officerCheckInList: 'officer-checkIn-list',
  jobListById: 'job-list-by-id',
  addToPreferredOfficer: 'add-to-preferred-officer',
  getOfficerPreferredList: 'get-officer-preferred-list',
  addToPrefferedListById: 'add-to-preffered-list-byId',
  getCMSDetail: 'get-cms-detail',
  getSingleOfficer: 'get-single-officer',
  addSendUsmail: 'add-send-us-mail',
  deletePreferredOfficer: 'delete-preferred-officer',
  transferOfficerList: 'transfer-officer-list',
  jobTransferOfficer: 'job-transfer-officer',
  changePassword: 'change-password',
  jobExtendRequest: 'extent-job-request',
  getSingleOfficerData: 'get-single-officer-data',
  acceptOrReject: 'accept-or-reject',
  officerRating: 'review-and-rating-officer',
  deleteAccount: 'delete-account',
  zipcodeList: 'all-zip-code',
  getAllSkill: 'get-all-skill',
};
